repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: 89f45610a846f56273a6c4290b3c42534175949e # v1.96.1
    hooks:
      - id: terraform_fmt
      - id: terraform_docs
      - id: terraform_trivy
        # decomment to skip ./terraform
        # args:
        # - --args=--skip-dirs="**/.terraform"
      - id: terraform_validate
        args:
          - --init-args=-lockfile=readonly
          - --args=-json
          - --args=-no-color
